#!/bin/sh

if [ "$1" = "clean" ] ; then
   echo "Cleaning..."
   rm -rf cordova-app
   rm -rf dist/*
   echo "Done!"
   exit
fi

mkdir -p dist
npm install
gulp build


if [ ! -d cordova-app ] ; then
  cordova create cordova-app naikus.github.io.stagestarter StageStarter --link-to=dist --verbose
  cp -r hooks cordova-app
  # copy the existing config.xml (Note the app id and name in this file will take precedence over the
  # cordova 'create' command above)
  cp src/config.xml cordova-app
  # copy the resources directory (splash screen, app icon, etc.)
  cp -r src/res cordova-app/
fi


cd cordova-app

# add the appropriate platform
cordova platforms add $1

if [ "$1" != "browser" ] ; then
  cordova plugin add cordova-plugin-inappbrowser
  cordova plugin add cordova-plugin-statusbar
  # cordova plugin add cordova-plugin-dialogs
  # cordova plugin add cordova-plugin-vibration
  cordova plugin add cordova-plugin-network-information
  cordova plugin add cordova-plugin-whitelist
fi


if [ "$1" = "ios" ] ; then
  # Add only ios specific plugins
fi


if [ "$1" = "andoird" ] ; then
  # Add only ios specific plugins
fi

cordova prepare
cd ..
