#!/bin/sh

if [ "$1" = "clean" ] ; then
   echo "Cleaning..."
   rm -rf cordova-app
   rm -rf dist
   echo "Done!"
   exit
fi

mkdir -p dist
gulp build

cordova create cordova-app naikus.github.io.swagpos SwagPos --link-to=./dist

# copy the existing config.xml (Note the app id and name in this file will take precedence over the
# cordova 'create' command above)
cp src/config.xml cordova-app

# copy the resources directory (splash screen, app icon, etc.)
cp -r src/res cordova-app/

cd cordova-app

if [ "$1" != "browser" ] ; then
  cordova plugin add cordova-plugin-inappbrowser
  cordova plugin add cordova-plugin-statusbar
  # cordova plugin add cordova-plugin-dialogs
  # cordova plugin add cordova-plugin-vibration
  cordova plugin add cordova-plugin-network-information
  cordova plugin add cordova-plugin-whitelist
fi


# add the appropriate platform
cordova platforms add $1
cordova prepare


# install local npm modules
cd ..
yarn install
